version: '3.3'
services:
  tor:
    image: alpine:latest
    container_name: tor_on_docker
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050:9050/tcp"
      - "53:5353/udp"
    volumes:
      - ./conf:/etc/tor/
      - ./shell_script:/root
    entrypoint: /root/entrypoint.sh
